services:
  mongo:
    image: mongo:7
    container_name: restatividade-mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: restatividade-api
    environment:
      - MONGO_URL=mongodb://mongo:27017/FatecVotorantim
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3000:3000'

volumes:
  mongo-data:
    driver: local
